### ISSUE TITLE
Suggest install with pipx in README

### ISSUE THREAD

**Issue by jacobtomlinson** [Cvaniak/NoteSH#1]
This looks like a really neat textual app!

You might want to direct folks to install it with [`pipx`](https://pypa.github.io/pipx/) rather than `pip` in the README. Pip will install it in whatever Python environment is currently active, which means it could get broken down the line and changing environments might remove it from the PATH.

Pipx creates a new venv for just the app and ensures always it's available.

**Comment by Cvaniak** [comment]
Thank you!
This is very good idea. I will update README with next update.

**Comment by nenkoru** [comment]
What about using Poetry as a dependency manager?
As well controlling the environment it has a lot of nice features one of which is fast dependency resolving and tracking of all the dependencies the dependency libraries rely upon.

Defacto its becoming the industry standard to initiate a Python project with.

**Comment by Cvaniak** [comment]
I did some small project in the past that did not have much interest, so for most of them my silly template was enough. 
But you are absolutely right, poetry nowadays is standard and this is already on my todo list.
I have problem with finishing projects so one of my strategy is to release fast. But then - oh boy, I need to face shame for my dirty code and things that I used to... but refactor is almost done :smile:

**Comment by nenkoru** [comment]
> I did some small project in the past that did not have much interest, so for most of them my silly template was enough. 
> 
> But you are absolutely right, poetry nowadays is standard and this is already on my todo list.
> 
> I have problem with finishing projects so one of my strategy is to release fast. But then - oh boy, I need to face shame for my dirty code and things that I used to... but refactor is almost done :smile: 

Well, I guess no one really cares about the quality of the code. The project itself is a pretty nice idea. And having implemented it asap attracts contributors to contribute and fix the issues if there are any.
So don't worry about the quality of the code. That's for whaf opensource exists for.

**Comment by jacobtomlinson** [comment]
Poetry is great, for any project that doesn't have complex compiled dependencies I agree it should be the defacto choice these days.

However, I would point out that this project is a TUI application, not a library or backend application, so `pipx` would be the right choice for the end user to install it with. For dev making it poetry based makes sense.

**Comment by nenkoru** [comment]
> Poetry is great, for any project that doesn't have complex compiled dependencies I agree it should be the defacto choice these days.
> 
> 
> 
> However, I would point out that this project is a TUI application, not a library or backend application, so `pipx` would be the right choice for the end user to install it with. For dev making it poetry based makes sense.

[But poetry provides a neat way to create a package and push it to PyPi](https://python-poetry.org/docs/libraries/#packaging)
So for the end user would the same API of using pip or pipx to install it.
Correct me if I am missing something

**Comment by jacobtomlinson** [comment]
Yeah, I think we are agreeing that `poetry` would be great for dev/publishing. This issue was discussing moving the README instructions from `pip` to `pipx`. I didn't want @Cvaniak to think the suggestion was to tell users to install with `poetry`.

Maybe it would be best to open a new issue to track moving publishing to `poetry`?

**Comment by nenkoru** [comment]
> Yeah, I think we are agreeing that `poetry` would be great for dev/publishing. This issue was discussing moving the README from `pip` to `pipx`. I didn't want @Cvaniak to think the suggestion was to tell users to install with `poetry`.
> 
> 
> 
> Maybe it would be best to open a new issue to track moving publishing to `poetry`?

Okay, got it. Apologies for misunderstanding.
+1 about creating a separate issue for adding Poetry as a dependency manager.
