### ISSUE TITLE
Error: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

### ISSUE THREAD

**Issue by finsteininvest** [Cvaniak/NoteSH#5]
Produced on a Mac after pip install notesh 

Successfully installed markdown-it-py-2.2.0 mdurl-0.1.2 notesh-0.4 pygments-2.14.0 rich-13.3.1 textual-0.9.1

and then calling notesh

**Comment by Cvaniak** [comment]
Thank you for letting me know.

I think it was because of missing `from __future__ import annotation` and now problem in new version should be fixed.

**Comment by finsteininvest** [comment]
Nice. Working, thank you
