### ISSUE TITLE
add to Textual gallery

### ISSUE THREAD

**Issue by zachvalenta** [Cvaniak/NoteSH#6]
https://www.textualize.io/gallery-instructions

Figure more people will be exposed to the project there as well.

**Comment by Cvaniak** [comment]
I have already done PR https://github.com/Textualize/textualize.io/pull/123 .
But looking on other issues, it requires some patience.
Thank you for thinking highly of this project!

**Comment by zachvalenta** [comment]
Aha, ok, didn't see you in the gallery so figured hadn't already submitted yet. Good to hear!
